[features]
seeds = false
skip-lint = false
[programs.devnet]
mygifproject = "DfvbZwDYrz12dwVnRtkubCMwL74iL8AE87e8sPvVWSxC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/mahmudsudo/.config/solana/id.json"


[scripts]
test = "node tests/mygifproject.js"

